const maximList = [
    "Be the change you wish to see in the world.",
    "A journey of a thousand miles begins with a single step.",
    "Knowledge is power.",
    "Actions speak louder than words.",
    "You reap what you sow.",
    "Where there's a will, there's a way.",
    "Honesty is the best policy.",
    "Practice makes perfect.",
    "The early bird catches the worm.",
    "Time is money.",
    "There's no time like the present.",
    "When in Rome, do as the Romans do.",
    "Fortune favors the bold.",
    "To thine own self be true.",
    "You can't judge a book by its cover.",
    "All's fair in love and war.",
    "If it ain't broke, don't fix it.",
    "The pen is mightier than the sword.",
    "Life is what you make it.",
    "Better late than never.",
    "When life gives you lemons, make lemonade.",
    "Fall down seven times, stand up eight.",
    "Tough times never last, but tough people do.",
    "The strongest steel is forged in the hottest fire.",
    "Smooth seas do not make skillful sailors.",
    "A setback is a setup for a comeback.",
    "What doesn't kill you makes you stronger.",
    "Adversity introduces a man to himself.",
    "The difference between stumbling blocks and stepping stones is how you use them.",
    "Resilience is not what happens to you, but how you react to it."]


    module.exports = maximList