const maximList = [
    "Be the change you wish to see in the world.",
    "A journey of a thousand miles begins with a single step.",
    "Knowledge is power.",
    "Actions speak louder than words.",
    "You reap what you sow.",
    "Where there's a will, there's a way.",
    "Honesty is the best policy.",
    "Practice makes perfect.",
    "The early bird catches the worm.",
    "Time is money.",
    "There's no time like the present.",
    "When in Rome, do as the Romans do.",
    "Fortune favors the bold.",
    "To thine own self be true.",
    "You can't judge a book by its cover.",
    "All's fair in love and war.",
    "If it ain't broke, don't fix it.",
    "The pen is mightier than the sword.",
    "Life is what you make it.",
    "Better late than never.",
    "When life gives you lemons, make lemonade.",
    "Fall down seven times, stand up eight.",
    "Tough times never last, but tough people do.",
    "The strongest steel is forged in the hottest fire.",
    "Smooth seas do not make skillful sailors.",
    "A setback is a setup for a comeback.",
    "What doesn't kill you makes you stronger.",
    "Adversity introduces a man to himself.",
    "The difference between stumbling blocks and stepping stones is how you use them.",
    "Resilience is not what happens to you, but how you react to it.",
    "If you want something you've never had, you must be willing to do something you've never done.",
    "Life is too short to waste time on things that don't matter.",
    "In the middle of every difficulty lies opportunity.",
    "A person who never made a mistake never tried anything new.",
    "We can't help everyone, but everyone can help someone.",
    "The best way to predict the future is to create it.",
    "The only person you are destined to become is the person you decide to be.",
    "If you don't stand for something, you will fall for anything.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
]


    module.exports = maximList