const themeList = [
    "Love",
    "Loss",
    "Friendship",
    "Betrayal",
    "Redemption",
    "Power",
    "Freedom",
    "Family",
    "Growth",
    "Time passing",
    "Identity",
    "Nature",
    "Justice",
    "Transformation",
    "Courage",
    "Coming of age",
    "Survival",
    "Good vs. evil",
    "War",
    "Oppression",
    "Social injustice",
    "Sacrifice",
    "Betrayal of trust",
    "Deception",
    "Dreams",
    "Loneliness",
    "Hope",
    "Fear",
    "Discovery",
    "Regret",
    "Innocence",
    "Experience",
    "Rebellion",
    "Forgiveness",
    "Isolation",
    "Ambition",
    "Betrayal of self",
    "Temptation",
    "Insanity",
    "Guilt",
    "Paranoia",
    "Secrets",
    "Powerlessness",
    "Transformation of self",
    "Corruption",
    "Prejudice",
    "Betrayal of country",
    "Alienation",
    "Redemption of self",
    "Corruption of power"
  ];

  module.exports = themeList